### PR TITLE
index: simplify intro

### PR DESCRIPTION
**Pull request by dunn**
Closes GH-44.

### CODE REVIEW

**Review by chrissyrissmeyer — CHANGES_REQUESTED** [review]
I'd like to see a sentence that expresses this concept be retained (although with better wording) "And it isn't just for software: books, papers, documentation, metadata, and anything that changes over time or needs to be shared can and should be stored in a version control system."

It's nice to reinforce that git isn't just for software development.

**Comment by dunn** [comment]
@chrissyrissmeyer how's that?

**Review by chrissyrissmeyer — APPROVED** [review]

**Comment by mcritchlow** [comment]
The only completely minor issue here is this is where we introduce Catsy Cline, which we then refer to in git commits, git config, etc. going forward. I don't think this is a big deal at all. In reality if we're going through this at the command line, we're not going to use Catsy anyway in the config (we'll be using whoever's laptop/account), so all the students are going to see is that account. So I think it's fine to just leave that alone, but want to see if ya'll agree.

**Comment by dunn** [comment]
Yeah I think it's fine to have a silly name in the commit message, even if we don't reference it anywhere else.

**Review by mcritchlow — APPROVED** [review]

**Pull request merged**
